- type: replace
  path: /instance_groups/name=victoria-metrics/jobs/name=victoria-metrics/properties/victoria-metrics?/http_auth?
  value:
    username: admin
    password: ((victoria_metrics_password))

- type: replace
  path: /variables?/-
  value:
    name: victoria_metrics_password
    type: password
