# Exporter jobs
- type: replace
  path: /instance_groups/name=victoria-metrics/jobs/-
  value:
    name: bosh_exporter
    release: victoria-metrics
    properties:
      bosh_exporter:
        bosh:
          url: "((bosh_url))"
          username: "((bosh_username))"
          password: "((bosh_password))"
          ca_cert: "((bosh_ca_cert))"
        metrics:
          environment: "((metrics_environment))"


# Grafana Dashboards
- type: replace
  path: /instance_groups/name=grafana/jobs/name=bosh_dashboards?/release
  value: victoria-metrics

- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/victoria-metrics/dashboard_folders/name=BOSH?/files/-
  value: /var/vcap/jobs/bosh_dashboards/bosh*.json

- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/victoria-metrics/dashboard_folders/name=VictoriaMetrics?/files/-
  value: /var/vcap/jobs/bosh_dashboards/prometheus*.json

# Prometheus Scrape Config
- type: replace
  path: /instance_groups/name=victoria-metrics/jobs/name=victoria-metrics/properties/victoria-metrics/scrape_configs/-
  value:
    job_name: bosh
    scrape_interval: 2m
    scrape_timeout: 1m
    static_configs:
      - targets:
        - localhost:9190

- type: replace
  path: /instance_groups/name=victoria-metrics/jobs/name=victoria-metrics/properties/victoria-metrics/scrape_configs/-
  value:
    job_name: cf
    scrape_interval: 4m
    scrape_timeout: 2m
    file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
    relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: cf_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9193"

- type: replace
  path: /instance_groups/name=victoria-metrics/jobs/name=victoria-metrics/properties/victoria-metrics/scrape_configs/-
  value:
    job_name: firehose
    file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
    relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: firehose_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9186"

- type: replace
  path: /instance_groups/name=victoria-metrics/jobs/name=victoria-metrics/properties/victoria-metrics/scrape_configs/-
  value:
    job_name: grafana
    file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
    relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: grafana
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:3000"

- type: replace
  path: /instance_groups/name=victoria-metrics/jobs/name=victoria-metrics/properties/victoria-metrics/scrape_configs/-
  value:
    job_name: postgres
    file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
    relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: postgres_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9187"