# A list of scrape configurations.
<% scrape_configs = p('victoria-metrics.scrape_configs', []).map do |scrape_config|

  scrape_config = scrape_config.clone
  scrape_config['tls_config'] = scrape_config['tls_config'].clone
  ['ca_contents', 'cert_contents', 'key_contents'].each { |key| scrape_config['tls_config'].delete(key) } if scrape_config['tls_config']
  scrape_config
end %>

scrape_configs: <%= scrape_configs.to_json %>

