releases:
- name: bosh-dns-aliases
  sha1: 48d96a53370ab1230fe36af9fb3725a33cc36811
  stemcell:
    os: ubuntu-jammy
    version: "1.80"
  url: https://storage.googleapis.com/cf-deployment-compiled-releases/bosh-dns-aliases-0.0.4-ubuntu-jammy-1.80-20230515-092007-526301549.tgz
  version: 0.0.4

addons:
- jobs:
  - name: bosh-dns-aliases
    properties:
      aliases:
      - domain: _.cell.service.cf.internal
        targets:
        - deployment: cf
          domain: bosh
          instance_group: diego-cell
          network: default
          query: _
        - deployment: cf
          domain: bosh
          instance_group: windows2019-cell
          network: default
          query: _
        - deployment: cf
          domain: bosh
          instance_group: isolated-diego-cell
          network: default
          query: _
      - domain: auctioneer.service.cf.internal
        targets:
        - deployment: cf
          domain: bosh
          instance_group: scheduler
          network: default
          query: q-s4
      - domain: bbs.service.cf.internal
        targets:
        - deployment: cf
          domain: bosh
          instance_group: diego-api
          network: default
          query: q-s4
      - domain: blobstore.service.cf.internal
        targets:
        - deployment: cf
          domain: bosh
          instance_group: singleton-blobstore
          network: default
          query: '*'
      - domain: cc-uploader.service.cf.internal
        targets:
        - deployment: cf
          domain: bosh
          instance_group: api
          network: default
          query: '*'
      - domain: cloud-controller-ng.service.cf.internal
        targets:
        - deployment: cf
          domain: bosh
          instance_group: api
          network: default
          query: '*'
      - domain: credhub.service.cf.internal
        targets:
        - deployment: cf
          domain: bosh
          instance_group: credhub
          network: default
          query: '*'
      - domain: doppler.service.cf.internal
        targets:
        - deployment: cf
          domain: bosh
          instance_group: doppler
          network: default
          query: '*'
      - domain: file-server.service.cf.internal
        targets:
        - deployment: cf
          domain: bosh
          instance_group: api
          network: default
          query: '*'
      - domain: gorouter.service.cf.internal
        targets:
        - deployment: cf
          domain: bosh
          instance_group: router
          network: default
          query: '*'
      - domain: locket.service.cf.internal
        targets:
        - deployment: cf
          domain: bosh
          instance_group: diego-api
          network: default
          query: '*'
      - domain: loggregator-trafficcontroller.service.cf.internal
        targets:
        - deployment: cf
          domain: bosh
          instance_group: log-api
          network: default
          query: '*'
      - domain: policy-server.service.cf.internal
        targets:
        - deployment: cf
          domain: bosh
          instance_group: api
          network: default
          query: '*'
      - domain: reverse-log-proxy.service.cf.internal
        targets:
        - deployment: cf
          domain: bosh
          instance_group: log-api
          network: default
          query: '*'
      - domain: routing-api.service.cf.internal
        targets:
        - deployment: cf
          domain: bosh
          instance_group: api
          network: default
          query: '*'
      - domain: silk-controller.service.cf.internal
        targets:
        - deployment: cf
          domain: bosh
          instance_group: diego-api
          network: default
          query: '*'
      - domain: sql-db.service.cf.internal
        targets:
        - deployment: cf
          domain: bosh
          instance_group: database
          network: default
          query: '*'
      - domain: ssh-proxy.service.cf.internal
        targets:
        - deployment: cf
          domain: bosh
          instance_group: scheduler
          network: default
          query: '*'
      - domain: tps.service.cf.internal
        targets:
        - deployment: cf
          domain: bosh
          instance_group: scheduler
          network: default
          query: '*'
      - domain: uaa.service.cf.internal
        targets:
        - deployment: cf
          domain: bosh
          instance_group: uaa
          network: default
          query: '*'
      - domain: nats.service.cf.internal
        targets:
        - deployment: cf
          domain: bosh
          instance_group: nats
          network: default
          query: '*'
      - domain: _.nats.service.cf.internal
        targets:
        - deployment: cf
          domain: bosh
          instance_group: nats
          network: default
          query: _
      - domain: log-cache.service.cf.internal
        targets:
        - deployment: cf
          domain: bosh
          instance_group: log-cache
          network: default
          query: '*'
    release: bosh-dns-aliases
  name: bosh-dns-aliases
  include:
    jobs:
    - name: grafana
      release: victoria-metrics
    - name: victoria-metrics
      release: victoria-metrics