{
 "title": "Victoria Metrics: Cloud Foundry Firehose Exporter",
 "tags": [ "victoria-metrics" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(firehose_total_envelopes_received, environment)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(firehose_total_envelopes_received{environment=~\"$environment\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Rate Envelopes & Metrics Received per second",
   "type": "graph",
   "description": "Number of envelopes and metrics received per second from Cloud Foundry Firehose during the last 5 minutes.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(firehose_total_envelopes_received{environment=~\"$environment\",instance=~\"$instance\"}[5m])",
     "legendFormat": "Envelopes ({{ instance }})"
    },
    {
     "expr": "rate(firehose_total_metrics_received{environment=~\"$environment\",instance=~\"$instance\"}[5m])",
     "legendFormat": "Metrics ({{ instance }})"
    }
   ]
  },
  {
   "title": "Total Envelopes & Metrics Received",
   "type": "graph",
   "description": "Cumulative number of envelopes and metrics received from Cloud Foundry Firehose.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(firehose_total_envelopes_received{environment=~\"$environment\",instance=~\"$instance\"}) by(instance)",
     "legendFormat": "Envelopes ({{ instance }})"
    },
    {
     "expr": "sum(firehose_total_metrics_received{environment=~\"$environment\",instance=~\"$instance\"}) by(instance)",
     "legendFormat": "Metrics ({{ instance }})"
    }
   ]
  },
  {
   "title": "Last Envelope Received",
   "type": "singlestat",
   "description": "When was the last envelope received from Cloud Foundry Firehose.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(firehose_last_envelope_received_timestamp{environment=~\"$environment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Last Metric Received",
   "type": "singlestat",
   "description": "When was the last metric received from Cloud Foundry Firehose.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(firehose_last_metric_received_timestamp{environment=~\"$environment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Slow Consumer Alert",
   "type": "singlestat",
   "description": "Whether a slow consumer alert has been received from Cloud Foundry Firehose.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(firehose_slow_consumer_alert{environment=~\"$environment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Rate Container Metrics per second",
   "type": "graph",
   "description": "Number of ContainerMetrics received and processed per second from Cloud Foundry Firehose during the last 5 minutes.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(firehose_total_container_metrics_received{environment=~\"$environment\",instance=~\"$instance\"}[5m])",
     "legendFormat": "Received ({{ instance }})"
    },
    {
     "expr": "rate(firehose_total_container_metrics_processed{environment=~\"$environment\",instance=~\"$instance\"}[5m])",
     "legendFormat": "Processed ({{ instance }})"
    }
   ]
  },
  {
   "title": "Total Container Metrics",
   "type": "graph",
   "description": "Cumulative number of ContainerMetrics received and processed from Cloud Foundry Firehose.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(firehose_total_container_metrics_received{environment=~\"$environment\",instance=~\"$instance\"}) by(instance)",
     "legendFormat": "Received ({{ instance }})"
    },
    {
     "expr": "sum(firehose_total_container_metrics_processed{environment=~\"$environment\",instance=~\"$instance\"}) by(instance)",
     "legendFormat": "Processed ({{ instance }})"
    }
   ]
  },
  {
   "title": "Container Metrics Cached",
   "type": "graph",
   "description": "Cumulative number of ContainerMetrics cached from Cloud Foundry Firehose.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(firehose_container_metrics_cached{environment=~\"$environment\",instance=~\"$instance\"}) by(instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Last Container Metric Received",
   "type": "singlestat",
   "description": "When was the last ContainerMetric received from Cloud Foundry Firehose.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(firehose_last_container_metric_received_timestamp{environment=~\"$environment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Rate Counter Events  per second",
   "type": "graph",
   "description": "Number of CounterEvents received and processed per second from Cloud Foundry Firehose during the last 5 minutes.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(firehose_total_counter_events_received{environment=~\"$environment\",instance=~\"$instance\"}[5m])",
     "legendFormat": "Received ({{ instance }})"
    },
    {
     "expr": "rate(firehose_total_counter_events_processed{environment=~\"$environment\",instance=~\"$instance\"}[5m])",
     "legendFormat": "Processed ({{ instance }})"
    }
   ]
  },
  {
   "title": "Total Counter Events",
   "type": "graph",
   "description": "Cumulative number of CounterEvents received and processed from Cloud Foundry Firehose.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(firehose_total_counter_events_received{environment=~\"$environment\",instance=~\"$instance\"}) by(instance)",
     "legendFormat": "Received ({{ instance }})"
    },
    {
     "expr": "sum(firehose_total_counter_events_processed{environment=~\"$environment\",instance=~\"$instance\"}) by(instance)",
     "legendFormat": "Processed ({{ instance }})"
    }
   ]
  },
  {
   "title": "Counter Events Cached",
   "type": "graph",
   "description": "Cumulative number of CounterEvents cached from Cloud Foundry Firehose.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(firehose_counter_events_cached{environment=~\"$environment\",instance=~\"$instance\"}) by(instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Last Counter Event Received",
   "type": "singlestat",
   "description": "When was the last CounterEvent received from Cloud Foundry Firehose.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(firehose_last_counter_event_received_timestamp{environment=~\"$environment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Rate HTTP Start Stop per second",
   "type": "graph",
   "description": "Number of HttpStartStops received and processed per second from Cloud Foundry Firehose during the last 5 minutes.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(firehose_total_http_start_stop_received{environment=~\"$environment\",instance=~\"$instance\"}[5m])",
     "legendFormat": "Received ({{ instance }})"
    },
    {
     "expr": "rate(firehose_total_http_start_stop_processed{environment=~\"$environment\",instance=~\"$instance\"}[5m])",
     "legendFormat": "Processed ({{ instance }})"
    }
   ]
  },
  {
   "title": "Total HTTP Start Stop",
   "type": "graph",
   "description": "Cumulative number of HttpStartStops received and processed from Cloud Foundry Firehose.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(firehose_total_http_start_stop_received{environment=~\"$environment\",instance=~\"$instance\"}) by(instance)",
     "legendFormat": "Received ({{ instance }})"
    },
    {
     "expr": "sum(firehose_total_http_start_stop_processed{environment=~\"$environment\",instance=~\"$instance\"}) by(instance)",
     "legendFormat": "Processed ({{ instance }})"
    }
   ]
  },
  {
   "title": "HTTP Start Stop Cached",
   "type": "graph",
   "description": "Cumulative number of HttpStartStops cached from Cloud Foundry Firehose.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(firehose_http_start_stop_cached{environment=~\"$environment\",instance=~\"$instance\"}) by(instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Last HTTP Start Stop Received",
   "type": "singlestat",
   "description": "When was the last HttpStartStop received from Cloud Foundry Firehose.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(firehose_last_http_start_stop_received_timestamp{environment=~\"$environment\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Rate Value Metrics per second",
   "type": "graph",
   "description": "Number of ValueMetrics received and processed persecond from Cloud Foundry Firehose during the last 5 minutes.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(firehose_total_value_metrics_received{environment=~\"$environment\",instance=~\"$instance\"}[5m])",
     "legendFormat": "Received ({{ instance }})"
    },
    {
     "expr": "rate(firehose_total_value_metrics_processed{environment=~\"$environment\",instance=~\"$instance\"}[5m])",
     "legendFormat": "Processed ({{ instance }})"
    }
   ]
  },
  {
   "title": "Total Value Metrics",
   "type": "graph",
   "description": "Cumulative number of ValueMetrics received and processed from Cloud Foundry Firehose.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(firehose_total_value_metrics_received{environment=~\"$environment\",instance=~\"$instance\"}) by(instance)",
     "legendFormat": "Received ({{ instance }})"
    },
    {
     "expr": "sum(firehose_total_value_metrics_processed{environment=~\"$environment\",instance=~\"$instance\"}) by(instance)",
     "legendFormat": "Processed ({{ instance }})"
    }
   ]
  },
  {
   "title": "Value Metrics Cached",
   "type": "graph",
   "description": "Cumulative number of ValueMetrics cached from Cloud Foundry Firehose.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(firehose_value_metrics_cached{environment=~\"$environment\",instance=~\"$instance\"}) by(instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Last Value Metric Received",
   "type": "singlestat",
   "description": "When was the last ValueMetric received from Cloud Foundry Firehose.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 20 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(firehose_last_value_metric_received_timestamp{environment=~\"$environment\",instance=~\"$instance\"})"
    }
   ]
  }
 ]
}